### ISSUE TITLE
Enabled Options & spin bot

### ISSUE THREAD

**Issue by Goodb1** [k-i-o/TClientPlus#2]
Seeing what options you have enabled in the client would be grate, so you dont have to go to the settings. and mostly having a custom Ui would be sick, some stuff like the photos i added (if possible).
![Immagine 2024-03-27 140132](https://github.com/k-i-o/TClientPlus/assets/152087278/7b47397c-9a96-4a64-a486-6ec3f9217cea)
![Immagine 2024-03-27 140250](https://github.com/k-i-o/TClientPlus/assets/152087278/9e18c3a3-5400-44a2-b124-328b9689a16b)

About the Spin-Bot, is impossible to use since it actually makes rotate your aim, maybe make it just a aesthetic option that only others can see, but witouth affecting where you want to aim.

**Comment by k-i-o** [comment]
oke i can do the first thing, but the second is impossible, i can do something that doesn't affect your aim (like the silent that already exist) but that move your texture, but others can't see it

**Comment by Goodb1** [comment]
Or maybe the client moves the aim but saves the position of the last mouse movement, so if you move it again it switches to the latest save. Pretty triggery
