### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by neversrakatan** [k-i-o/TClientPlus#3]
Allow interaction with replay via bindings(Useful not on ddnet maps)

**Comment by k-i-o** [comment]
wdym

**Comment by ArkashaG** [comment]
Add a button to remove the line in the replay of the recording, because of it the FPS drops to the minimum values. Or tell me where this tile is so that it can be removed.

**Comment by ArkashaG** [comment]
I think he wants you to add a quick switch between recordings in the replay mode.
