### ISSUE TITLE
Idea №2

### ISSUE THREAD

**Issue by ArkashaG** [k-i-o/TClientPlus#4]
Add a button to remove the line in the replay of the recording, because of it the FPS drops to the minimum values. Or tell me where this tile is so that it can be removed.

**Comment by k-i-o** [comment]
Remove the Blue line while playing or the green line that indicate where is the start of the record?

**Comment by ArkashaG** [comment]
The blue line at the moment of repeating the recording greatly reduces FPS

**Comment by ArkashaG** [comment]
FPS drops because this line is animated and because of this it is radvet

**Comment by k-i-o** [comment]
Ye ok I got it, in the next update there will be the possibility to disable it

**Comment by k-i-o** [comment]
b91077969b7c5844cfcd5995627b400282ca095d done
